#!/usr/bin/env python3
"""CSV -> Markdown table renderer for the 3 conference papers.

For each venue, reads the canonical results CSVs and emits a single
`results/tables.md` containing publication-ready Markdown tables.
The paper draft can copy-paste from there (or, for an automated
pipeline, the body's table-block can be replaced via simple sed).

Per-venue rules:

ECEL  results/modality_pools.csv      -> Table 1 (modality-stratified pools)
      results/modality_qbetween.csv   -> Table 2 (Q_between)
      results/interaction_terms.csv   -> Table 3 (interaction terms)
ICEEL results/asia_subset_pools.csv   -> Table 1 (Asian subset pools)
      results/hofstede_meta_regression.csv -> Table 2 (Hofstede slopes)
ICERI results/cross_tab_pools.csv     -> Table 1 (cell-level pools)
      results/interaction_terms.csv   -> Table 2 (interaction terms)

Numeric rounding follows APA-7 / IEEE conference convention:
  r, β, t, z  ->  3 decimals
  p           ->  3 decimals (with "<.001" floor)
  Q, χ²       ->  2 decimals
  df, k, N    ->  integer
  CI          ->  3-decimal bracketed

Usage:
    python3 metaanalysis/conference_submissions/scripts/render_tables.py
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
WORKSPACE = ROOT / "metaanalysis" / "conference_submissions"


def fmt_r(x: str) -> str:
    try:
        return f"{float(x):.3f}"
    except (ValueError, TypeError):
        return str(x)


def fmt_p(x: str) -> str:
    try:
        v = float(x)
        if v < 0.001:
            return "<.001"
        return f"{v:.3f}".lstrip("0")  # ".045"
    except (ValueError, TypeError):
        return str(x)


def fmt_q(x: str) -> str:
    try:
        return f"{float(x):.2f}"
    except (ValueError, TypeError):
        return str(x)


def fmt_int(x: str) -> str:
    try:
        return str(int(float(x)))
    except (ValueError, TypeError):
        return str(x)


def fmt_pct(x: str) -> str:
    try:
        v = float(x)
        return f"{v:.0f}%"
    except (ValueError, TypeError):
        return str(x)


def md_table(headers: list[str], rows: list[list[str]]) -> str:
    head = "| " + " | ".join(headers) + " |"
    sep = "|" + "|".join("---" for _ in headers) + "|"
    body = "\n".join("| " + " | ".join(r) + " |" for r in rows)
    return f"{head}\n{sep}\n{body}\n"


# ----------------------------------------------------------------------
# ECEL
# ----------------------------------------------------------------------
def ecel_tables() -> str:
    out = ["# ECEL — auto-rendered tables\n",
           "Generated by `scripts/render_tables.py`. Do not hand-edit; "
           "rerun the pipeline (`scripts/run_modality_meta.py`) and "
           "this script.\n"]

    pools = WORKSPACE / "ecel" / "results" / "modality_pools.csv"
    if pools.exists():
        out.append("## Table 1. Modality-stratified pooled correlations\n")
        rows = []
        with open(pools, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append([
                    row["trait"],
                    row["modality"],
                    fmt_int(row["k"]),
                    fmt_int(row["N_total"]),
                    fmt_r(row["r_pooled"]),
                    f"[{fmt_r(row['r_ci_lo'])}, {fmt_r(row['r_ci_hi'])}]",
                    fmt_pct(row["I2"]),
                ])
        out.append(md_table(
            ["Trait", "Modality", "k", "N", "r", "95% CI", "I²"], rows,
        ))

    qbet = WORKSPACE / "ecel" / "results" / "modality_qbetween.csv"
    if qbet.exists():
        out.append("\n## Table 2. Q_between random-effects contrast across modality levels (df = 1)\n")
        rows = []
        with open(qbet, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append([
                    row["trait"],
                    fmt_q(row["Q_between"]),
                    fmt_p(row["p_between"]),
                ])
        out.append(md_table(["Trait", "Q_between", "p"], rows))

    inter = WORKSPACE / "ecel" / "results" / "interaction_terms.csv"
    if inter.exists():
        out.append("\n## Table 3. Long-format weighted-OLS interaction model\n")
        rows = []
        with open(inter, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append([
                    row.get("term", ""),
                    fmt_r(row.get("coef", row.get("estimate", ""))),
                    fmt_r(row.get("se", "")),
                    fmt_q(row.get("t", row.get("z", ""))),
                    fmt_p(row.get("p", "")),
                ])
        out.append(md_table(["Term", "β (Fisher z)", "SE", "t / z", "p"], rows))

    return "\n".join(out)


# ----------------------------------------------------------------------
# ICEEL
# ----------------------------------------------------------------------
def iceel_tables() -> str:
    out = ["# ICEEL — auto-rendered tables\n",
           "Generated by `scripts/render_tables.py`.\n"]

    asia = WORKSPACE / "iceel" / "results" / "asia_subset_pools.csv"
    if asia.exists():
        out.append("## Table 1. Asian-subset pooled correlations\n")
        rows = []
        with open(asia, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append([
                    row["trait"],
                    fmt_int(row["k"]),
                    fmt_int(row["N_total"]),
                    fmt_r(row["r_pooled"]),
                    f"[{fmt_r(row['r_ci_lo'])}, {fmt_r(row['r_ci_hi'])}]",
                    fmt_pct(row["I2"]),
                ])
        out.append(md_table(["Trait", "k", "N", "r", "95% CI", "I²"], rows))

    hof = WORKSPACE / "iceel" / "results" / "hofstede_meta_regression.csv"
    if hof.exists():
        out.append("\n## Table 2. Hofstede single-dimension meta-regression (descriptive only; df_resid = 0)\n")
        rows = []
        with open(hof, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append([
                    row.get("trait", ""),
                    row.get("dimension", ""),
                    fmt_r(row.get("slope", row.get("beta", ""))),
                    fmt_r(row.get("se", "")),
                ])
        out.append(md_table(["Trait", "Hofstede dim.", "Slope (Fisher z / dim)", "SE"], rows))

    return "\n".join(out)


# ----------------------------------------------------------------------
# ICERI
# ----------------------------------------------------------------------
def iceri_tables() -> str:
    out = ["# ICERI — auto-rendered tables\n",
           "Generated by `scripts/render_tables.py`.\n"]

    cross = WORKSPACE / "iceri" / "results" / "cross_tab_pools.csv"
    if cross.exists():
        out.append("## Table 1. Cross-tab cell-level pooled correlations (k ≥ 2 only)\n")
        rows = []
        with open(cross, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                k = row.get("k", "0")
                try:
                    if int(float(k)) < 2:
                        continue
                except (ValueError, TypeError):
                    continue
                rows.append([
                    row["trait"],
                    row.get("level", ""),
                    row.get("discipline", ""),
                    fmt_int(k),
                    fmt_int(row.get("N_total", "")),
                    fmt_r(row.get("r_pooled", "")),
                    f"[{fmt_r(row.get('r_ci_lo', ''))}, {fmt_r(row.get('r_ci_hi', ''))}]",
                ])
        out.append(md_table(
            ["Trait", "Level", "Discipline", "k", "N", "r", "95% CI"], rows,
        ))

    inter = WORKSPACE / "iceri" / "results" / "interaction_terms.csv"
    if inter.exists():
        out.append("\n## Table 2. Long-format weighted-OLS interaction model\n")
        rows = []
        with open(inter, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append([
                    row.get("term", ""),
                    fmt_r(row.get("coef", row.get("estimate", ""))),
                    fmt_r(row.get("se", "")),
                    fmt_q(row.get("t", row.get("z", ""))),
                    fmt_p(row.get("p", "")),
                ])
        out.append(md_table(["Term", "β (Fisher z)", "SE", "t / z", "p"], rows))

    return "\n".join(out)


def main():
    n_written = 0
    for venue, render in [("ecel", ecel_tables), ("iceel", iceel_tables), ("iceri", iceri_tables)]:
        out_path = WORKSPACE / venue / "results" / "tables.md"
        text = render()
        out_path.write_text(text, encoding="utf-8")
        print(f"Wrote {out_path} ({len(text.splitlines())} lines)")
        n_written += 1
    print(f"\n{n_written} table-files emitted.")
    sys.exit(0)


if __name__ == "__main__":
    main()
